kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  alertmanager.yml: |-
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      group_by: [cluster]
      # If an alert isn't caught by a route, send it slack.
      receiver: slack-all
      routes:
        - match:
            severity: slack
          receiver: slack-all
    receivers:
    - name: 'slack-all'
      slack_configs:
      - channel: '# alert-manager'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        api_url: 'https://hooks.slack.com/services/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'

